FROM node:20-bullseye AS build
WORKDIR /workspace
COPY package*.json ./
COPY . .
RUN npm ci
ARG SERVICE_NAME
RUN npx nx run ${SERVICE_NAME}:build

FROM node:20-bullseye
WORKDIR /app
ARG SERVICE_DIR
COPY --from=build /workspace/${SERVICE_DIR}/dist ./dist
COPY --from=build /workspace/node_modules ./node_modules
ENV NODE_ENV=production
CMD ["node", "dist/main.js"]
