ARG NODE_VERSION=20.20.0

FROM node:${NODE_VERSION}-bullseye-slim AS build
WORKDIR /repo

COPY package.json package-lock.json nx.json tsconfig.base.json tsconfig.json ./
COPY . .

RUN npm ci
RUN npx nx run ${SERVICE_NAME}:build
RUN npx nx run ${SERVICE_NAME}:prune

FROM node:${NODE_VERSION}-bullseye-slim
WORKDIR /app

ENV NODE_ENV=production
ENV NODE_PATH=/app/workspace_modules

COPY --from=build /repo/${SERVICE_DIR}/dist ./dist
COPY --from=build /repo/${SERVICE_DIR}/dist/package.json ./package.json
COPY --from=build /repo/${SERVICE_DIR}/dist/package-lock.json ./package-lock.json
COPY --from=build /repo/${SERVICE_DIR}/dist/workspace_modules ./workspace_modules

RUN npm ci --omit=dev

CMD ["node", "dist/main.js"]
