services:
  election-service:
    image: ghcr.io/gaboToro/election-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
      - ./env/business.env
    environment:
      PORT: "3006"
    ports:
      - "3006:3006"
    restart: unless-stopped

  voting-service:
    image: ghcr.io/gaboToro/voting-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
      - ./env/business.env
    environment:
      PORT: "3002"
    ports:
      - "3002:3002"
    restart: unless-stopped

  results-service:
    image: ghcr.io/gaboToro/results-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
      - ./env/business.env
    environment:
      PORT: "3004"
    ports:
      - "3004:3004"
    restart: unless-stopped

  blockchain-service:
    image: ghcr.io/gaboToro/blockchain-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
      - ./env/business.env
    environment:
      PORT: "3003"
    ports:
      - "3003:3003"
    restart: unless-stopped

  reporting-service:
    image: ghcr.io/gaboToro/reporting-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
      - ./env/business.env
    environment:
      PORT: "3012"
    ports:
      - "3012:3012"
    restart: unless-stopped
