services:
  api-gateway:
    image: ghcr.io/gabotoro/api-gateway:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
      - ./env/identity.env
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped

  auth-service:
    image: ghcr.io/gabotoro/auth-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
    environment:
      PORT: "3001"
    ports:
      - "3001:3001"
    restart: unless-stopped

  user-service:
    image: ghcr.io/gabotoro/user-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
    environment:
      PORT: "3005"
    ports:
      - "3005:3005"
    restart: unless-stopped

  rate-limiter-service:
    image: ghcr.io/gabotoro/rate-limiter-service:${IMAGE_TAG:-qa}
    env_file:
      - ./env/common.env
    environment:
      PORT: "3010"
    ports:
      - "3010:3010"
    restart: unless-stopped
