services:
  postgres:
    image: postgres:16
    container_name: dvs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dvs
      POSTGRES_PASSWORD: DigitalVoting123
      POSTGRES_DB: dvs
    ports:
      - "5432:5432"
    volumes:
      - dvs_pg:/var/lib/postgresql/data
      - ../../sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dvs -d dvs"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:7
    container_name: dvs-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: dvs_user
      MONGO_INITDB_ROOT_PASSWORD: dvs_pass_123
    ports:
      - "27017:27017"
    volumes:
      - dvs_mongo:/data/db

  redis:
    image: redis:7
    container_name: dvs-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  dvs_pg:
  dvs_mongo:
